#!/bin/env bash

if [ -z "$1" ]; then
    echo "Missing parameter: service name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Missing parameter: tenant"
    exit 1
fi

SERVICE=$1
TENANT=$2

echo "Deploying $SERVICE to tenant $TENANT"

cdk deploy --context service="$SERVICE" --context tenant="$TENANT"